appsilon/blueprints/views/__init__.py
from flask import Blueprint

from appsilon.blueprints.views.routes import (
    index,
    movies,
    directors,
    genres,
    movies_by_director,
    movies_by_genre,
    movie_details,
)

bp = Blueprint("views", __name__, template_folder="templates")

bp.add_url_rule("/", view_func=index)
bp.add_url_rule("/movies", view_func=movies)
bp.add_url_rule("/directors", view_func=directors)
bp.add_url_rule("/genres", view_func=genres)
bp.add_url_rule("/movies_by_director/<int:director_id>", view_func=movies_by_director)
bp.add_url_rule("/movies_by_genre/<int:genre_id>", view_func=movies_by_genre)
bp.add_url_rule("/movie_details/<int:movie_id>", view_func=movie_details)


def init_app(app):
    app.register_blueprint(bp)

appsilon/blueprints/views/routes.py
from flask import render_template, request

from appsilon.ext.assets.transactions import (
    get_movies,
    get_directors,
    get_genres,
    get_movie_by_id,
    get_director_by_id,
    get_genre_by_id,
    get_genres_by_movie,
    get_directors_by_movie,
    get_movies_by_director,
    get_movies_by_genre,
)


def index():
    return render_template("index.html")


def movies():
    page = int(request.args.get("page", 1))
    per_page = int(request.args.get("per_page", 10))
    movies = get_movies(page=page, per_page=per_page)
    context = {
        "movies": movies.items,
        "pagination": movies,
    }
    return render_template("movies.html", **context)


def directors():
    page = int(request.args.get("page", 1))
    per_page = int(request.args.get("per_page", 10))
    directors = get_directors(page=page, per_page=per_page)
    context = {
        "directors": directors.items,
        "pagination": directors,
    }
    return render_template("directors.html", **context)


def genres():
    page = int(request.args.get("page", 1))
    per_page = int(request.args.get("per_page", 10))
    genres = get_genres(page=page, per_page=per_page)
    context = {
        "genres": genres.items,
        "pagination": genres,
    }
    return render_template("genres.html", **context)


def movies_by_director(director_id):
    context = {
        "director": get_director_by_id(director_id),
        "movies": get_movies_by_director(director_id),
    }
    return render_template("movies_by_director.html", **context)


def movies_by_genre(genre_id):
    context = {
        "genre": get_genre_by_id(genre_id),
        "movies": get_movies_by_genre(genre_id),
    }
    return render_template("movies_by_genre.html", **context)


def movie_details(movie_id):
    context = {
        "movie": get_movie_by_id(movie_id),
        "genres": get_genres_by_movie(movie_id),
        "directors": get_directors_by_movie(movie_id),
    }
    return render_template("movie_details.html", **context)

appsilon/blueprints/views/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <link
    rel="icon"
    type="image/x-icon"
    href="{{ url_for('static', filename='favicon.ico') }}"
  />
  <link
    rel="stylesheet"
    type="text/css"
    href="{{ url_for('static', filename='style.css') }}"
  />
  <link
    rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Limelight"
  />
  <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
  />

  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav>
      <a href="/">Home</a>
      <span class="star-icon">&#9733;</span>
      <a href="{{ url_for('views.movies') }}">Movies</a>
      <span class="star-icon">&#9733;</span>
      <a href="{{ url_for('views.directors') }}">Directors</a>
      <span class="star-icon">&#9733;</span>
      <a href="{{ url_for('views.genres') }}">Genres</a>
    </nav>

    {% block content %} {% endblock %}
  </body>
  <footer>
    <div class="footer-content">
      <p>
        <small>
          &copy; 2023 Designed and developed by
          <a href="https://github.com/CavalcanteLucas"
            ><i class="fab fa-github"></i
          > Lucas Cavalcante</a>
        </small>
      </p>
    </div>
  </footer>
</html>

appsilon/blueprints/views/templates/directors.html
{% extends 'base.html' %} {% block title %}{{ config.get('TITLE') }}{% endblock %} {% block content %}

<div class="container-box">
  <div class="box-content">
    <h1>Directors</h1>
    <ul>
      {% for director in directors %}
      <p>
        <span class="star-bullet">&#9733;</span>
        <a
          href="{{ url_for('views.movies_by_director', director_id=director.id) }}"
          >{{ director.name }}</a
        >
      </p>
      {% endfor %}
    </ul>
  </div>

  {% include 'pagination.html' %}
</div>

{% endblock %}

appsilon/blueprints/views/templates/genres.html
{% extends 'base.html' %} {% block title %}{{ config.get('TITLE') }}{% endblock%} {% block content %}

<div class="container-box">
  <div class="box-content">
    <h1>Genres</h1>
    <ul>
      {% for genre in genres %}
      <p>
        <span class="star-bullet">&#9733;</span>
        <a
          href="{{ url_for('views.movies_by_genre', genre_id=genre.id) }}"
          class="genre-title"
          >{{ genre.name }}</a
        >
      </p>
      {% endfor %}
    </ul>
  </div>

  {% include 'pagination.html' %}
</div>

{% endblock %}

appsilon/blueprints/views/templates/index.html
{% extends 'base.html' %} {% block title %}{{ config.get('TITLE') }}{% endblock %} {% block content %}

<div class="title-box">
  <h1 class="title-text">{{ config.get('TITLE') }}</h1>
  <p class="title-subtitle">
    Discover the Cinematic Universe: Explore Movies, Directors, and Genres on
    IMDb
  </p>
</div>

{% endblock %}

appsilon/blueprints/views/templates/movie_details.html
{% extends 'base.html' %} {% block title %}{{ config.get('TITLE') }}{% endblock %} {% block content %}

<div class="container-box">

  <div class="box-content">
    <h1>
      {{ movie.title }} ({{ movie.year }}) -
      <a href="{{ movie.url }}"
        ><span style="text-transform: uppercase">{{ movie.imdb }}</span></a
      >
    </h1>
    <h2>Directors</h2>
    <ul>
      {% for director in directors %}
      <p>
        <span class="star-bullet">&#9733;</span
        ><a
          href="{{ url_for('views.movies_by_director', director_id=director.id) }}"
          >{{ director.name }}</a
        >
      </p>
      {% endfor %}
    </ul>
    <h2>Genres</h2>
    <ul>
      {% for genre in genres %}
      <p class="genre-title">
        <span class="star-bullet">&#9733;</span
        ><a
          href="{{ url_for('views.movies_by_genre', genre_id=genre.id) }}"
          class="genre-title"
          >{{ genre.name }}</a
        >
      </p>
      {% endfor %}
    </ul>
  </div>

</div>
{% endblock %}

appsilon/blueprints/views/templates/movies.html
{% extends 'base.html' %} {% block title %}{{ config.get('TITLE') }}{% endblock %} {% block content %}

<div class="container-box">
  <div class="box-content">
    <h1>Movies</h1>
    <ul>
      {% for movie in movies %}
      <p>
        <span class="star-bullet">&#9733;</span>
        <a href="{{ url_for('views.movie_details', movie_id=movie.id) }}"
          >{{ movie.title }} ({{ movie.year }})</a
        >
      </p>
      {% endfor %}
    </ul>
  </div>

  {% include 'pagination.html' %}
</div>

{% endblock %}

appsilon/blueprints/views/templates/movies_by_director.html
{% extends 'base.html' %} {% block title %}{{ config.get('TITLE') }}{% endblock %} {% block content %}

<div class="container-box">
  <div class="box-content">
    <h1>{{ director.name }}</h1>
    <ul>
      {% for movie in movies %}
      <p>
        <span class="star-bullet">&#9733;</span
        ><a href="{{ url_for('views.movie_details', movie_id=movie.id) }}"
          >{{ movie.title }} ({{ movie.year }})</a
        >
      </p>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

appsilon/blueprints/views/templates/movies_by_genre.html
{% extends 'base.html' %} {% block title %}{{ config.get('TITLE') }}{% endblock %} {% block content %}

<div class="container-box">
  <div class="box-content">
    <h1 class="genre-title">{{ genre.name }}</h1>
    <ul>
      {% for movie in movies %}
      <p>
        <span class="star-bullet">&#9733;</span
        ><a href="{{ url_for('views.movie_details', movie_id=movie.id) }}"
          >{{ movie.title }} ({{ movie.year }})</a
        >
      </p>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

appsilon/blueprints/views/templates/pagination.html
<div class="box-pagination">
  <ul class="pagination">
    <div class="box-prev-link">
      {% if pagination.has_prev %}
      <li class="page-item">
        <a
          class="page-link"
          href="{{ request.path }}?page={{ pagination.prev_num }}&per_page={{ pagination.per_page }}"
          >&#10229;</a
        >
      </li>
      {% endif %}
    </div>

    {% for page_num in pagination.iter_pages(left_edge=1, left_current=2,
    right_current=3, right_edge=1) %} {% if page_num %} {% if pagination.page ==
    page_num %}
    <li class="page-item active">
      <a
        class="page-link"
        href="{{ request.path }}?page={{ page_num }}&per_page={{ pagination.per_page }}"
        >{{ page_num }}</a
      >
    </li>
    {% else %}
    <li class="page-item">
      <a
        class="page-link"
        href="{{ request.path }}?page={{ page_num }}&per_page={{ pagination.per_page }}"
        >{{ page_num }}</a
      >
    </li>
    {% endif %} {% else %}
    <li class="page-item disabled">
      <span class="page-link">&hellip;</span>
    </li>
    {% endif %} {% endfor %}
    <div class="box-next-link">
      {% if pagination.has_next %}
      <li class="page-item">
        <a
          class="page-link"
          href="{{ request.path }}?page={{ pagination.next_num }}&per_page={{ pagination.per_page }}"
          >&#10230;</a
        >
      </li>
      {% endif %}
    </div>
  </ul>
</div>